### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by jackiewillen** [kmohrf/vue-on-click-outside#3] opened 2018-01-30 08:19 UTC
js error ErrorEventbubbles: falsecancelBubble: falsecancelable: truecolno: 0composed: falsecurrentTarget: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}defaultPrevented: falseerror: nulleventPhase: 0filename: ""isTrusted: truelineno: 0message: "Script error."path: [Window]returnValue: truesrcElement: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}target: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}timeStamp: 261504.85000000003type: "error"__proto__: ErrorEvent
webpack-internal:///736:30 Uncaught TypeError: callback is not a function
    at Object.check (webpack-internal:///736:30)
    at eval (webpack-internal:///736:64)
    at Array.forEach (<anonymous>)
    at HTMLHtmlElement.eval (webpack-internal:///736:63)

i use this plugin as your example in vue component,but always have this problem

**Comment by kmohrf** [comment] 2018-01-30 11:04
well… without a copy of your actual code I might not be able to help you. but it looks like you’re passing something to the directive that is not a function. does your directive call look like this `v-on-click-outside="close"` or like this `v-on-click-outside="close()"`. It should be the former and `close` must be a method you defined in your component. if that doesn’t help, please attach the code you’re using to this issue.

**Comment by jackiewillen** [comment] 2018-01-31 02:46
@kmohrf  but when i want to use v-on-click-outside="close(item)".It will always have this problem.I use this in a v-for,every item has a popup,so i want to close the item when the item lose focus.So i need to pass a parameter 'item'  in to it.

**Comment by kmohrf** [comment] 2018-01-31 14:21
directives are not event listeners (I'll probably have to blame myself for giving the impression of it by calling it *on-click*). they simply don’t work that way. it expects a function and the statement in the directive is evaluated during component instantation meaning that everything `v-on-click-outside` receives when you call it the way you do is the return value of `close(item)` which is probably `undefined`. 

you may want to try `v-on-click-outside="() => close(item)"`.

**Comment by kmohrf** [comment] 2018-02-01 14:16
@jackiewillen did that solve your problem?

**Comment by kmohrf** [comment] 2018-04-20 01:24
closing because no further feedback has been provided and the problem seems to have been caused by an incorrect use of the directive

**Closed as completed by kmohrf** 2018-04-20 01:24 UTC
